travis:
  secure:
    BINSTAR_TOKEN: D+q28DOCHyeOd8ce6TawyMe23mXuYTsw5ctDAZeoSkXEG4mRc9rC8SuXv634hpn1qd8McIKa7nCnePOsnY5O+A/v4FNCirKiCEn5r65GWwLETkF9eifqBuqWSb+HoxkfV6cfcDoAwKtFwyTADwv1LGl7jVTz+KAToCuN90zaPQ+G5tbLTd3vitwBLKkiE8Qp1TE3NaV1BaEJRihrWNt6N7kv83D8byfz+ALMNsvirpmZ7WSNhf/WUhqxT+j003i+ZbUWtXwvJMc9aFEyBsHBA1Kn9Np9Z8XRc7a2AfvC3w4ph9F7hbeEwyEoHzbsINSfI9F265egVj/SN+AiJSNQiJwn68YaE+FXJTZw/6i/RFKl5Zqhex8pHZDkRA/cyWmYTUYwZgWTgZ+9C9SfloLfCwxiuNZ5gZSuc5M0XueiMf5Vnxw+p0QJlNuf1eBZIv900o4vUozftX05N9emjAauwDYEDh48B20YeTvBC32lvopA7mLXooiWlWY2L2fQZUzVaXoaw+zt214y7rtcVC6Tqjqotw7foTfRd+34jQH4PvCKTERqy6g0W3Vo231H1GR6ZjF9GrQXGFb3UUjoL4q47Cxhs/9vUhpU1iCAgpUe/C6uhkIlwZ7ce5R5NOnz0PLFqo1+vete7dFJIytgITOSE7W9N2VJcSXHlyUAaGeGzQw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
