travis:
  secure:
    BINSTAR_TOKEN: JrWfx/Lu452Bxe+UcpZXg6orpYedaLoJU+h6ufwzMWlkdU38nzJmByzqpMNOjsIYfstoePHtRWZscvqS95BzaW7GJ9zdxNF41NFOzOIsvtaLkFxI0yardyxbRkQnCioVajaZ756zwmOU662iRSU0YoPkYh480XL9DaU80TJMgFP0ehxwiFCcTQoDKjAO8J6hNPm09XsdozfVqrQLFmG50mC5IQSb1i1CXMuF+LFwZa6r3ggM9A2/Mymsf6FV53hygktG8EOAoKTCElKRfLuOvmii5jidxe1VLwuUZKqfLiqMUmoXXjfRSiydvGpQh/cNo1MHgL/Pl9+kSlhqn2jvfICyBMdfyx50dIjDyd5N2qLk+ICqa115VCt4wjS1dgPOVrDmwXKmeZVkQ5EKQDy1cSRB45ZotBU576Ak10tQBZoIfbs1w5JpWW9a+eqBV+NpJ2LPrD8MxcO675GLKDbH8rMGjD7BbFa1EL5W0bVgBDw94lv96GnhskpgAMYOb+jZBfcHNEUWKzkKeYcY1HoB+PPF746g0+tsy0pibGaTpK8/cl7rIbPlTp07n76i3sxbNlU4J2pxBHkuEHYhlnkswTG5d8vX9/HF6aGlUpEdKtEV905W9cTBJzxFCF1z8U966IewwCiRBwocNMh6fEb1wxtDCt8e6yPHyIe6DrLMqEE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
